### ISSUE TITLE
OptiX SDK 7.7.0 - FUNCTION_TABLE_MISMATCH

### ISSUE THREAD

**Issue by SveSop** [SveSop/wine-nvoptix#28]
Since i decided to do some testing of OptiX SDK's compiled with CUDA 11.4 to get around that pesky "cudacheck" i cant figure out, i came across a new error.
`Caught exception: OPTIX_ERROR_FUNCTION_TABLE_SIZE_MISMATCH: Optix call 'optixInit()' failed`

The `optixQueryFunctionTable` line reads this on SDK 7.6:
`trace:nvoptix:optixQueryFunctionTable (68, 0, (nil), (nil), 0x140068470, 376)`
and this on SDK 7.7:
`trace:nvoptix:optixQueryFunctionTable (84, 0, (nil), (nil), 0x140068470, 384)`

So.. Difference in tablesize between 7.6 and 7.7 - Check
[https://github.com/SveSop/wine-nvoptix/blob/master/src/nvoptix.c#L83](https://github.com/SveSop/wine-nvoptix/blob/master/src/nvoptix.c#L83) satisfied - Check
(I also checked that the implementation of ABI84 function table is the same size as the `optixQueryFunctionTable` call requests, and it matches)

Still the demo/sample code that does this "check" fails.. 
`OPTIX_CHECK( optixInit() );`

So.,. CUDA SDK >=11.6 got a new sort of "check" that cant be bypassed, and now OptiX SDK 7.7 got some sort of new "check" that cant be bypassed??? Color me suspicious..... Ideas welcome @Saancreed 

PS. The SDK 7.7 samples run fine native Linux, so afaik drivers++ should handle the windows compiled ones just as fine?

**Comment by Saancreed** [comment]
I had a look at Nvidia's headers and `384` indeed seems to be the correct table size for ABI version 84 / API version 7.7.0, but right now I'm on 525 Vulkan dev driver which doesn't seem to support OptiX 7.7 (I get `ERROR: initOptiX() initOptiXFunctionTable() failed: 7801` which is `OPTIX_ERROR_UNSUPPORTED_ABI_VERSION` when trying to run `intro_denoiser` from `OptiX_Apps` repo on Linux) and I'm waiting for next 535 release before switching to that.

Anyway, this is strange. The implementation of `optixInit` as seen in https://raytracing-docs.nvidia.com/optix7/api/optix__stubs_8h_source.html can only ever return `OPTIX_ERROR_FUNCTION_TABLE_SIZE_MISMATCH` if this is what we return from `wine-nvoptix`, which returns what the native driver returns to us, which… doesn't make any sense.

Have you tried logging what does the native `libnvoptix.so` return to us?

```c
    OptixResult result;

    switch (abiId)
    {
        case 84:
            result = optixQueryFunctionTable_84(numOptions, optionKeys, optionValues, functionTable, sizeOfTable);
        …
    }

    TRACE("(%d, %u, %p, %p, %p, %zu): ret %d\n", abiId, numOptions, optionKeys, optionValues, functionTable, sizeOfTable, result);

    return result;
```

If it _does_ give us the `OPTIX_ERROR_FUNCTION_TABLE_SIZE_MISMATCH` result, then why does it work for native OptiX applications? If it doesn't, then how can this error ever appear for the Windows application running in Wine?

I can try to debug this myself once I untangle my driver situation and then I'll also be able to check how Windows NV driver behaves because I actually have a working installation of Windows 11 on this laptop.

**Comment by SveSop** [comment]
> If it _does_ give us the `OPTIX_ERROR_FUNCTION_TABLE_SIZE_MISMATCH` result, then why does it work for native OptiX applications? If it doesn't, then how can this error ever appear for the Windows application running in Wine?
> 
Well.. it does NOT it seems...

Inserting a dummy call in the "switch" part of nvoptix.c and TRACE the value of ret somewhat like this:

```
OptixResult ret = OPTIX_ERROR_FUNCTION_TABLE_SIZE_MISMATCH;
ret = poptixQueryFunctionTable(84, 0, 0, 0, functionTable, 384);
TRACE("Return code: %d\n", ret);
```
Returns 0 -     `OPTIX_SUCCESS                               = 0,`
Any other number than `384`  returns     `OPTIX_ERROR_FUNCTION_TABLE_SIZE_MISMATCH    = 7802,`

So, from what i am able to gather, the Linux driver returns what we would think.... Atleast from the wine-nvoptix implementation and its call to liboptix.so. 

> I can try to debug this myself once I untangle my driver situation and then I'll also be able to check how Windows NV driver behaves because I actually have a working installation of Windows 11 on this laptop.

I guess the next step would be to write some small binary just doing this call and check if 384 returns success both in Linux AND Windows? Will see if i can whip something incredibly small together, but i am not really sure where to start, since the demo/sample thingys provided here is nothing near "minor" 😃

**Comment by SveSop** [comment]
Hrmpf... Calling it like this:
`ret = optixQueryFunctionTable_84(numOptions, optionKeys, optionValues, functionTable, 384);`
fails with 7802... 
So.. What error did i make? lol

calling:
`ret = optixQueryFunctionTable_68(numOptions, optionKeys, optionValues, functionTable, 376);`
returns 0 - Success

So.. Hmm... I am certain i have made MORE typo's some place, and it is not some sinister plan here.. 🤣

**Comment by SveSop** [comment]
One of the issues i have is that afaik i cant run both Visual Studio 2019 and 2022 in the same windows install - and cuda SDK 11.4 is not compatible with VS2022.. thus i could not test OptiX demo's compiled with 2022 and cuda 12.xx (due to the issue with CUDA). But i set up a 2nd windows machine so i can do that now... and this was why i got around to do the actual testing.

Easy fix - should have caught that before - but atleast i got around to do some fiddling with it again 😄 
Thanks for doing some checking, and sorry for the noise @Saancreed

**Comment by Saancreed** [comment]
No worries, I'm glad you were able to figure that out. I feel like this entire process of dumping wrappers for a new table, hooking it up and updating ABI numbers could be automated somehow to make it a little less error-prone. But that's an adventure for another day :sweat_smile:

**Comment by SveSop** [comment]
> No worries, I'm glad you were able to figure that out. I feel like this entire process of dumping wrappers for a new table, hooking it up and updating ABI numbers could be automated somehow to make it a little less error-prone. But that's an adventure for another day 😅

Yeah.. Then again it is not thaaat often its updated SDK wise... 

It would probably have been caught if i had not cut corners and ASSUMED it worked without testing due to this pesky "need CUDA < 11.5" thingy.. But will hopefully be a bit more careful next time and actually run newer SDK's compiled with older CUDA 😝
